services:

  postgres:
    image: postgres:17
    container_name: swiss-owt-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: swiss_owt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: